### ISSUE TITLE
Whitelisting Automation

### ISSUE THREAD

**Issue by Alziibun** [PerditionPvE/meggido#5]
Staff want some automation for whitelisting.

`AddUser` - This command is used to add new players to the whitelist
`adduser "<Username>" <Password>`
STDOUT: "User <Username> created with the password..." 
 
## To-do

- [ ] Password generation
- [ ] Allow staff to approve or deny white list requests
- [ ] send `adduser` through RCON
- [ ] store login information so that it can be retrieved later
- [ ] send the login information to the user
- [ ] ask the user to enable DMs for the server if not available
